theme: jekyll-theme-slate
title: gsimcli - Geostatistical simulation for the homogenisation and interpolation of climate data
description: Geostatistical simulation for the homogenisation and interpolation of climate data
show_downloads: "true"
google_analytics: UA-48357296-1